HTTP_ADDR = "0.0.0.0"
HTTP_PORT = "8080"
ENVIRONMENT = "DEV"
CONTEXT_PATH = "/"
DB_MYSQL_USERNAME = ""
DB_MYSQL_PASSWORD = "123456aA!"
DB_MYSQL_HOST = "127.0.0.1"
DB_MYSQL_PORT = 3306
DB_MYSQL_DATABASE = "xd_working_trial"
DB_MYSQL_MAX_IDLE_CONNECTIONS = 5
DB_MYSQL_MAX_OPEN_CONNECTIONS = 5
DB_MYSQL_CONNECTION_MAX_LIFETIME = 300


