
name: Test

on:
  push:
    branches:
      - '**'

  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    name: Test
    container: golang:1.18
    runs-on: [self-hosted, shared-k8s-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Test
        run: go test
